const KEY = Object.freeze({
  MY_ALL_SCHEDULE: 'MY_SCHEDULE',
  ALL_PROFESSOR: 'ALL_PROFESSOR',
  PROFESSOR: 'PROFESSOR',
  ALL_AVAILABLE_TIME: 'ALL_AVAILABLE_TIME',
});

export const QUERY = Object.freeze({
  KEY,
});
